achievements/breakingBad.achievement.js
achievibitDB.js
eventManager.js
package.json
utilities.js

currently, this is a temporary stucture.
But at least now the main code is more readable

splitting things up

---

achievibitDB.js
eventManager.js
index.js
package.json

- install `nconf` to manage given params better
- write **Treasure** mechanism
- fix some **DB** updates to be more safe (update only the fields we need and let the **DB** do more work)

Implement treasure system

---

achievements/meeseek.achievement.js
eventManager.js

Solving many issues in a single pull request

Add achievement for solving many issues

---

achievements/biWinning.achievement.js

[BUG] fix case of no statuses to check gives the bi-winning achievement

---

index.js

resolves #47
related to badges/shields#866

change Cache-Control header to what people of http://shields.io/ suggested

---

achievibitDB.js

Fetch the reactions on the pull request description

[FEATURE] Fetch the pull request reactions

---

CONTRIBUTING.MD
LICENSE
README.md

- make `achievibit` more welcoming for people to contribute to
- Add a welcome paragraph
- Add more robust details on how to run and code for `achievibit`
- Mention future tests

start updating the CONTRIBUTING.MD file to include more info

---

.gitignore
.travis.yml
package.json
test/achievibitDB.js
test/eventManager.js
test/utilities.js

- integrate mocha, chai, and istanbul [relates to #26]
- write a few simple tests to check things out [relates to #26]

Add tests to achievibit

---

.travis.yml

- testing `travis` out with `achievibit`
(Free text here with additional photos, wikis, and additional needed information)

[DO NOT SUBMIT] add node.js version to .travis.yml

---

test/achievibitDB.js
test/eventManager.js
test/useGithubBot.achievement.js
test/utilities.js

- change tests names to correct syntax
- add general tests for `useGithubBot` achievement

[TESTS] Fix some test names and add tests for useGithubBot achievement

---

.gitignore
package.json
test/optimusPrime.specs.js
test/theGodfatherConsigliere.specs.js

- added an `html` reporter for `mocha.js`
- added **tests** for **Optimus Prime** and **The Godfather Consigliere**

[TESTS] Even more tests

---

index.js
package.json
test/e2e.js
test/utilities.js

- add some E2E tests (well... **almost E2E**. working without a real database. `monkey.js`)
- add more `utilities.js` tests. Need to start making or using a mock library

[TESTS] E2e tests + more utilities.js tests

---

.travis.yml
index.js
test/doubleReview.specs.js
test/e2e.js
test/helpingHand.specs.js
test/labelBabyJunior.specs.js
test/meeseek.specs.js
test/member.specs.js
test/neverGoFullRetard.specs.js
utilities.js

- add port flag to cli 
- run E2E tests not on the default port
- add more tests for achievements
- fix indentation in `utilities.js`

Coverage increase

---

achievementsTest/acuu.achievement.js
eventManager.js

- support accumulative achievements

[FEATURE] support accumulative achievements

---

package.json

Closes #80
https://greenkeeper.io/
- change short synopsis I [resolves #00]
> additional info about this mission
- change short synopsis II (mission without additional info)
- change short synopsis III
(Free text here with additional photos, wikis, and additional needed information)

fix(package): update node-rest-client to version 3.0.5

---

README.md
package.json

- update some libraries and check that `achievibit` still works
- fix our broken readme

Get up to date - fix little things that are overdue

---

app/models/configurationService.js
index.js
package.json
views/blog.nunjucks
views/index.nunjucks

- replace swig to nunjucks
Should not effect the actual app since the syntax is the same
Also, added a console.log to test what's wrong with firebase on heroku

Update swig to nunjucks

---

app/models/configurationService.js

fix the debugging log

---

app/models/configurationService.js
app/models/userService.js

- Should bring achievibit back online [resolves #109]
> needed to escape the `\n`'s in the private key

escape \n in private key + remove debugging log

---

views/blog.nunjucks

- Fix broken user profile template (**blog.nunjucks aka blog.html**) [resolves #115 ]
> fixed some missed diffrences between `swig` and `nunjucks`

fix blog template differences between swig and nunjucks

---

views/blog.nunjucks
views/index.nunjucks

should fix analytics reporting

fix events for links

---

views/blog.nunjucks
views/index.nunjucks

last fix for analytics (I hope)

---

index.js

- If user entered the heroku site or anything else, they should be redirected to the correct path (our custom domain)
> Should not happen locally

[Feature] Redirect to custom domain

---

package.json

chore(package): update nunjucks to version 3.1.3

---

src/db-test.module.ts
src/modules/repos/repos.service.spec.ts
src/modules/users/users.service.spec.ts

First pull request on `next` branch.
I'm basically testing the **Heroku Review Apps** for achievibit V2

fix: move closeDatabase to be a static method of module

---

.commit-template
commitlint.config.js
package-lock.json
package.json

Also added a commit-template for git UIs that support it (like gitkraken)

chore(commits): integrate husky, commmitlint and commitizen
